from setuptools import setup, find_packages

setup(
    name='lexicographic_ppo',
    version='0.1.0',
    description='Lexicographic Proximal Policy Optimization for multi-objective reinforcement learning',
    author='Your Name',
    author_email='your.email@example.com',
    url='https://github.com/ntorqulu/lexicographic_ppo.git',
    packages=find_packages(where='src'),
    package_dir={'': 'src'},
    include_package_data=True,
    install_requires=[
        'cloudpickle==3.0.0',
        'contourpy==1.2.0',
        'cycler==0.12.1',
        'filelock==3.13.1',
        'fonttools==4.49.0',
        'fsspec==2024.2.0',
        'gym==0.26.2',
        'gym-notices==0.0.8',
        'Jinja2==3.1.3',
        'kiwisolver==1.4.5',
        'MarkupSafe==2.1.5',
        'matplotlib==3.8.3',
        'mpmath==1.3.0',
        'MultiAgentEthicalGathering @ git+https://github.com/maymac00/MultiAgentEthicalGatheringGame.git@a2c97e84fea9e3f185819e663d179dbf909721c0',
        'networkx==3.2.1',
        'numpy==1.26.4',
        'packaging==24.0',
        'pillow==10.2.0',
        'pyparsing==3.1.2',
        'python-dateutil==2.9.0.post0',
        'six==1.16.0',
        'sympy==1.12',
        'torch~=2.2.2',
        'typing_extensions==4.10.0',
        'pandas~=2.2.2',
        'seaborn~=0.13.2',
        'scipy~=1.13.1',
    ],
    classifiers=[
        'Development Status :: 3 - Alpha',
        'Intended Audience :: Developers',
        'Intended Audience :: Science/Research',
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
        'Topic :: Scientific/Engineering :: Artificial Intelligence',
    ],
    keywords='reinforcement learning, PPO, multi-objective, lexicographic',
    python_requires='>=3.7',
)
